## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [15]:
from sklearn.model_selection import train_test_split, KFold
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)

In [16]:
X_train

array([[ 20,  21,  22,  23,  24],
       [160, 161, 162, 163, 164],
       [710, 711, 712, 713, 714],
       [725, 726, 727, 728, 729],
       [545, 546, 547, 548, 549],
       [720, 721, 722, 723, 724],
       [ 50,  51,  52,  53,  54],
       [310, 311, 312, 313, 314],
       [560, 561, 562, 563, 564],
       [730, 731, 732, 733, 734],
       [830, 831, 832, 833, 834],
       [  0,   1,   2,   3,   4],
       [990, 991, 992, 993, 994],
       [765, 766, 767, 768, 769],
       [350, 351, 352, 353, 354],
       [615, 616, 617, 618, 619],
       [320, 321, 322, 323, 324],
       [220, 221, 222, 223, 224],
       [815, 816, 817, 818, 819],
       [140, 141, 142, 143, 144],
       [200, 201, 202, 203, 204],
       [540, 541, 542, 543, 544],
       [775, 776, 777, 778, 779],
       [780, 781, 782, 783, 784],
       [125, 126, 127, 128, 129],
       [115, 116, 117, 118, 119],
       [920, 921, 922, 923, 924],
       [735, 736, 737, 738, 739],
       [405, 406, 407, 408, 409],
       [195, 1

In [17]:
y_train

array([1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.])

In [13]:
X_test

array([[475, 476, 477, 478, 479]])

In [14]:
y_test

array([0.])